#!/usr/bin/env sh

pwdddc="$(ls ddc || echo "NOINSTDDC")"
pathddc="$(which ddc || echo "NODDC")"

if [ $pwdddc = "NOINSTDDC" ]; then
    if [ $pathddc = "NODDC" ]; then
      echo "No ddc in $pwd and no ddc in $PATH so exiting now."
      exit 1
    else
      echo "ddc found in $PATH but not in $PWD"
    fi
  else
    if [ $pathddc = "NODDC" ]; then
      echo "ddc found in $pwd but not in $PATH"
      echo "please install ./ddc to /usr/local/bin as a super user then run this installer again"
      echo
      echo "example, do this as root, do this with sudo, first:"
      echo "    cp ./ddc /usr/local/bin"
      echo "    chmod +x /usr/local/bin/ddc"
      echo
      echo
      exit 0
    else
      echo "ddc found"
    fi
fi

ls encryptor_template || exit 1

echo "type the template name then press enter"
read templatename

cp encryptor_template ~/Desktop/"$templatename" || exit 1

chmod +x ~/Desktop/$templatename

echo "enter name for $templatename target directory"
read enctarget

mkdir ~/Desktop/$enctarget

echo "entering vim to edit the $templatename copy"

sleep 3

vim ~/Desktop/$templatename

echo "interactive ddc template install complete"
